minVersion: "2.15.0"
changelog:
  policy: auto

artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
      - 'build-multiplatform-image-ghcr-amd64'
      - 'build-multiplatform-image-ghcr-arm64'
      - 'Create multi-platform manifest'

targets:
  - name: github
  - id: release
    name: docker
    source: ghcr.io/getsentry/uptime-checker
    target: ghcr.io/getsentry/uptime-checker
  - id: latest
    name: docker
    source: ghcr.io/getsentry/uptime-checker
    target: ghcr.io/getsentry/uptime-checker
    targetFormat: '{{{target}}}:latest'
