steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'create-builder'
    waitFor: ['-']
    args: ['buildx', 'create', '--driver', 'docker-container', '--name', 'container', '--use']

  # Login to GHCR
  - name: "gcr.io/cloud-builders/docker"
    id: "ghcr-login"
    waitFor: ["create-builder"]
    entrypoint: "bash"
    args:
      - "-c"
      - "docker login ghcr.io --username $$GHCR_USER --password-stdin <<< $$GHCR_PAT"
    secretEnv: ["GHCR_USER", "GHCR_PAT"]
  
  # Login to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    id: "dockerhub-auth"
    waitFor: ["ghcr-login"]
    entrypoint: "bash"
    args:
      - "-c"
      - "docker login --username=$$DOCKERHUB_USER --password-stdin <<< $$DOCKERHUB_PAT"
    secretEnv: ["DOCKERHUB_USER", "DOCKERHUB_PAT"]


  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    waitFor: ['dockerhub-auth']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euxo pipefail
        
        # Build and push with version tags
        docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/image:$COMMIT_SHA \
            -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/image:$SHORT_SHA \
            -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/image:nightly \
            -t ghcr.io/$_GHCR_OWNER/$REPO_NAME:$COMMIT_SHA \
            -t ghcr.io/$_GHCR_OWNER/$REPO_NAME:$SHORT_SHA \
            -t ghcr.io/$_GHCR_OWNER/$REPO_NAME:nightly \
            -t $_DOCKERHUB_OWNER/$REPO_NAME:$COMMIT_SHA \
            -t $_DOCKERHUB_OWNER/$REPO_NAME:$SHORT_SHA \
            -t $_DOCKERHUB_OWNER/$REPO_NAME:nightly \
            --label org.opencontainers.image.revision=$COMMIT_SHA \
            --label org.opencontainers.image.version=$COMMIT_SHA \
            --label org.opencontainers.image.title=$REPO_NAME \
            --label org.opencontainers.vendor="Sentry" \
            --label org.opencontainers.image.source=https://github.com/$REPO_FULL_NAME \
            --label org.opencontainers.image.url=https://github.com/$REPO_FULL_NAME \
            --cache-from $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/image:nightly \
            --sbom true \
            --provenance="mode=max" \
            --build-arg UPTIME_CHECKER_GIT_REVISION=$COMMIT_SHA \
            .

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/ghcr_user/versions/latest
      env: GHCR_USER
    - versionName: projects/${PROJECT_ID}/secrets/ghcr_pat/versions/latest
      env: GHCR_PAT 
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub_user/versions/latest
      env: DOCKERHUB_USER
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub_pat/versions/latest
      env: DOCKERHUB_PAT

substitutions:
  _DOCKERHUB_OWNER: "getsentry"
  _GHCR_OWNER: "getsentry"

options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 25
