steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/uptime-checker/image:$COMMIT_SHA-cloudbuild',
        '.',
      ]

options:
  machineType: 'E2_HIGHCPU_8'
