name: Release GHCR Versioned Image

on:
  release:
    types: [prereleased, released]

jobs:
  release-ghcr-version-tag:
    permissions:
      packages: write # required to push to ghcr

    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release version
        env:
          REPOSITORY: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
        run: |
          docker buildx imagetools create --tag \
            ghcr.io/"$REPOSITORY":"$REF_NAME" \
            ghcr.io/"$REPOSITORY":"$SHA"
